[package]
name = "waifu4me"
author = "kenjitheman"
description = "A CLI tool to fetch images from waifu.pics"
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.9"
reqwest = "0.11.22"
